# Generated by Django 5.0 on 2023-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainscrollmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainscrollmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
